import { Level } from '../types/game';

export const BUILT_IN_CAMPAIGN_LEVELS: Level[] = [
  {
    id: 1,
    name: "Level 1 (Intro Maze)",
    board: { width: 7, height: 7 },
    arrows: [
      { id: "a_1", direction: "RIGHT", points: [{ x: 4, y: 2 }, { x: 4, y: 0 }, { x: 5, y: 0 }] },
      { id: "a_2", direction: "UP", points: [{ x: 6, y: 5 }, { x: 4, y: 5 }, { x: 4, y: 4 }] },
      { id: "a_3", direction: "DOWN", points: [{ x: 5, y: 3 }, { x: 6, y: 3 }, { x: 6, y: 4 }] },
      { id: "a_4", direction: "DOWN", points: [{ x: 5, y: 1 }, { x: 6, y: 1 }, { x: 6, y: 2 }] },
      { id: "a_5", direction: "RIGHT", points: [{ x: 2, y: 0 }, { x: 2, y: 2 }, { x: 3, y: 2 }] },
      { id: "a_6", direction: "RIGHT", points: [{ x: 0, y: 2 }, { x: 0, y: 0 }, { x: 1, y: 0 }] },
      { id: "a_7", direction: "UP", points: [{ x: 0, y: 6 }, { x: 0, y: 4 }] },
      { id: "a_8", direction: "LEFT", points: [{ x: 2, y: 4 }, { x: 2, y: 6 }, { x: 1, y: 6 }] },
      { id: "a_9", direction: "DOWN", points: [{ x: 3, y: 3 }, { x: 1, y: 3 }, { x: 1, y: 4 }] },
      { id: "a_10", direction: "UP", points: [{ x: 5, y: 6 }, { x: 3, y: 6 }, { x: 3, y: 5 }] }
    ],
    difficulty: 1,
    parMoves: 10,
    patternType: "CAMPAIGN",
    seed: 1,
    difficultyScore: 1.0
  },
  {
    id: 2,
    name: "Level 2 (Coffee Cup)",
    board: { width: 10, height: 10 },
    arrows: [
      { id: "a_1", direction: "UP", points: [{ x: 1, y: 2 }, { x: 2, y: 2 }, { x: 2, y: 1 }] },
      { id: "a_2", direction: "UP", points: [{ x: 9, y: 5 }, { x: 9, y: 3 }] },
      { id: "a_3", direction: "UP", points: [{ x: 8, y: 7 }, { x: 9, y: 7 }, { x: 9, y: 6 }] },
      { id: "a_4", direction: "RIGHT", points: [{ x: 3, y: 6 }, { x: 3, y: 7 }, { x: 4, y: 7 }] },
      { id: "a_5", direction: "LEFT", points: [{ x: 7, y: 6 }, { x: 5, y: 6 }] },
      { id: "a_6", direction: "DOWN", points: [{ x: 7, y: 2 }, { x: 7, y: 4 }] },
      { id: "a_7", direction: "RIGHT", points: [{ x: 3, y: 2 }, { x: 6, y: 2 }] },
      { id: "a_8", direction: "UP", points: [{ x: 5, y: 5 }, { x: 6, y: 5 }, { x: 6, y: 3 }] },
      { id: "a_9", direction: "RIGHT", points: [{ x: 1, y: 3 }, { x: 3, y: 3 }] },
      { id: "a_10", direction: "UP", points: [{ x: 3, y: 5 }, { x: 1, y: 5 }, { x: 1, y: 4 }] },
      { id: "a_11", direction: "LEFT", points: [{ x: 5, y: 4 }, { x: 2, y: 4 }] },
      { id: "a_12", direction: "UP", points: [{ x: 4, y: 8 }, { x: 2, y: 8 }, { x: 2, y: 7 }] }
    ],
    difficulty: 1,
    parMoves: 12,
    patternType: "CAMPAIGN",
    seed: 2,
    difficultyScore: 1.2
  },
  {
    id: 3,
    name: "Level 3 (Sweet Heart)",
    board: { width: 10, height: 10 },
    arrows: [
      { id: "a_1", direction: "RIGHT", points: [{ x: 6, y: 2 }, { x: 6, y: 1 }, { x: 8, y: 1 }] },
      { id: "a_2", direction: "DOWN", points: [{ x: 2, y: 7 }, { x: 4, y: 7 }, { x: 4, y: 8 }] },
      { id: "a_3", direction: "DOWN", points: [{ x: 2, y: 5 }, { x: 4, y: 5 }, { x: 4, y: 6 }] },
      { id: "a_4", direction: "UP", points: [{ x: 7, y: 3 }, { x: 8, y: 3 }, { x: 8, y: 2 }] },
      { id: "a_5", direction: "UP", points: [{ x: 7, y: 7 }, { x: 7, y: 5 }] },
      { id: "a_6", direction: "RIGHT", points: [{ x: 5, y: 8 }, { x: 5, y: 7 }, { x: 6, y: 7 }] },
      { id: "a_7", direction: "DOWN", points: [{ x: 6, y: 3 }, { x: 6, y: 6 }] },
      { id: "a_8", direction: "RIGHT", points: [{ x: 1, y: 6 }, { x: 3, y: 6 }] },
      { id: "a_9", direction: "DOWN", points: [{ x: 0, y: 4 }, { x: 1, y: 4 }, { x: 1, y: 5 }] },
      { id: "a_10", direction: "DOWN", points: [{ x: 1, y: 1 }, { x: 1, y: 3 }] },
      { id: "a_11", direction: "LEFT", points: [{ x: 3, y: 3 }, { x: 3, y: 1 }, { x: 2, y: 1 }] },
      { id: "a_12", direction: "UP", points: [{ x: 4, y: 4 }, { x: 2, y: 4 }, { x: 2, y: 2 }] },
      { id: "a_13", direction: "LEFT", points: [{ x: 5, y: 4 }, { x: 5, y: 2 }, { x: 4, y: 2 }] },
      { id: "a_14", direction: "LEFT", points: [{ x: 9, y: 2 }, { x: 9, y: 4 }, { x: 8, y: 4 }] }
    ],
    difficulty: 2,
    parMoves: 14,
    patternType: "CAMPAIGN",
    seed: 3,
    difficultyScore: 1.5
  },
  {
    id: 4,
    name: "Level 4 (Round Ring)",
    board: { width: 11, height: 11 },
    arrows: [
      { id: "a_1", direction: "LEFT", points: [{ x: 5, y: 1 }, { x: 3, y: 1 }] },
      { id: "a_2", direction: "DOWN", points: [{ x: 7, y: 6 }, { x: 9, y: 6 }, { x: 9, y: 7 }] },
      { id: "a_3", direction: "LEFT", points: [{ x: 4, y: 9 }, { x: 4, y: 8 }, { x: 3, y: 8 }] },
      { id: "a_4", direction: "DOWN", points: [{ x: 8, y: 4 }, { x: 9, y: 4 }, { x: 9, y: 5 }] },
      { id: "a_5", direction: "UP", points: [{ x: 6, y: 8 }, { x: 8, y: 8 }, { x: 8, y: 7 }] },
      { id: "a_6", direction: "LEFT", points: [{ x: 7, y: 3 }, { x: 7, y: 1 }, { x: 6, y: 1 }] },
      { id: "a_7", direction: "UP", points: [{ x: 7, y: 5 }, { x: 6, y: 5 }, { x: 6, y: 4 }] },
      { id: "a_8", direction: "UP", points: [{ x: 4, y: 7 }, { x: 6, y: 7 }, { x: 6, y: 6 }] },
      { id: "a_9", direction: "RIGHT", points: [{ x: 1, y: 7 }, { x: 3, y: 7 }] },
      { id: "a_10", direction: "DOWN", points: [{ x: 1, y: 4 }, { x: 1, y: 6 }] },
      { id: "a_11", direction: "LEFT", points: [{ x: 5, y: 6 }, { x: 2, y: 6 }] },
      { id: "a_12", direction: "DOWN", points: [{ x: 2, y: 2 }, { x: 2, y: 4 }] },
      { id: "a_13", direction: "LEFT", points: [{ x: 5, y: 2 }, { x: 3, y: 2 }] },
      { id: "a_14", direction: "UP", points: [{ x: 4, y: 5 }, { x: 3, y: 5 }, { x: 3, y: 3 }] },
      { id: "a_15", direction: "LEFT", points: [{ x: 5, y: 5 }, { x: 5, y: 3 }, { x: 4, y: 3 }] },
      { id: "a_16", direction: "UP", points: [{ x: 7, y: 9 }, { x: 5, y: 9 }, { x: 5, y: 8 }] }
    ],
    difficulty: 2,
    parMoves: 16,
    patternType: "CAMPAIGN",
    seed: 4,
    difficultyScore: 1.8
  },
  {
    id: 5,
    name: "Level 5 (Labyrinth 23)",
    board: { width: 10, height: 10 },
    arrows: [
      { id: "a_1", direction: "LEFT", points: [{ x: 1, y: 8 }, { x: 1, y: 9 }, { x: 0, y: 9 }] },
      { id: "a_2", direction: "LEFT", points: [{ x: 2, y: 3 }, { x: 2, y: 1 }, { x: 1, y: 1 }] },
      { id: "a_3", direction: "LEFT", points: [{ x: 4, y: 0 }, { x: 4, y: 1 }, { x: 3, y: 1 }] },
      { id: "a_4", direction: "LEFT", points: [{ x: 6, y: 1 }, { x: 6, y: 0 }, { x: 5, y: 0 }] },
      { id: "a_5", direction: "DOWN", points: [{ x: 1, y: 7 }, { x: 0, y: 7 }, { x: 0, y: 8 }] },
      { id: "a_6", direction: "DOWN", points: [{ x: 3, y: 4 }, { x: 1, y: 4 }, { x: 1, y: 5 }] },
      { id: "a_7", direction: "LEFT", points: [{ x: 7, y: 6 }, { x: 7, y: 5 }, { x: 6, y: 5 }] },
      { id: "a_8", direction: "RIGHT", points: [{ x: 5, y: 8 }, { x: 5, y: 6 }, { x: 6, y: 6 }] },
      { id: "a_9", direction: "RIGHT", points: [{ x: 2, y: 8 }, { x: 2, y: 6 }, { x: 4, y: 6 }] },
      { id: "a_10", direction: "UP", points: [{ x: 6, y: 9 }, { x: 4, y: 9 }, { x: 4, y: 8 }] },
      { id: "a_11", direction: "LEFT", points: [{ x: 3, y: 8 }, { x: 3, y: 9 }, { x: 2, y: 9 }] },
      { id: "a_12", direction: "LEFT", points: [{ x: 9, y: 9 }, { x: 7, y: 9 }] },
      { id: "a_13", direction: "DOWN", points: [{ x: 8, y: 7 }, { x: 9, y: 7 }, { x: 9, y: 8 }] },
      { id: "a_14", direction: "DOWN", points: [{ x: 8, y: 0 }, { x: 9, y: 0 }, { x: 9, y: 1 }] },
      { id: "a_15", direction: "RIGHT", points: [{ x: 7, y: 3 }, { x: 7, y: 1 }, { x: 8, y: 1 }] },
      { id: "a_16", direction: "UP", points: [{ x: 6, y: 4 }, { x: 8, y: 4 }, { x: 8, y: 2 }] },
      { id: "a_17", direction: "RIGHT", points: [{ x: 5, y: 4 }, { x: 5, y: 2 }, { x: 6, y: 2 }] },
      { id: "a_18", direction: "RIGHT", points: [{ x: 0, y: 4 }, { x: 0, y: 2 }, { x: 1, y: 2 }] }
    ],
    difficulty: 3,
    parMoves: 18,
    patternType: "CAMPAIGN",
    seed: 5,
    difficultyScore: 2.0
  }
];
