-- Sample SQL with 100 Verified Solvable Levels
INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 1', 'Handcrafted level 1001', 6, 6, 1, 'published', '{"id":1001,"name":"Introductory Challenge 1","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1001,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 2', 'Handcrafted level 1002', 5, 5, 1, 'published', '{"id":1002,"name":"Introductory Challenge 2","board":{"width":5,"height":5},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":3,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":3,"y":3},{"x":1,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1002,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 3', 'Handcrafted level 1003', 6, 6, 1, 'published', '{"id":1003,"name":"Introductory Challenge 3","board":{"width":6,"height":6},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":4,"y":2},{"x":4,"y":4}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":3,"y":4},{"x":1,"y":4}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":3},{"x":1,"y":2}]}],"difficulty":1,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1003,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 4', 'Handcrafted level 1004', 5, 5, 1, 'published', '{"id":1004,"name":"Introductory Challenge 4","board":{"width":5,"height":5},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":3,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":3,"y":2},{"x":3,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1004,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 5', 'Handcrafted level 1005', 6, 6, 1, 'published', '{"id":1005,"name":"Introductory Challenge 5","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1005,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 6', 'Handcrafted level 1006', 5, 5, 1, 'published', '{"id":1006,"name":"Introductory Challenge 6","board":{"width":5,"height":5},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":3,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":3,"y":3},{"x":1,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1006,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 7', 'Handcrafted level 1007', 6, 6, 1, 'published', '{"id":1007,"name":"Introductory Challenge 7","board":{"width":6,"height":6},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":4,"y":2},{"x":4,"y":4}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":3,"y":4},{"x":1,"y":4}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":3},{"x":1,"y":2}]}],"difficulty":1,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1007,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 8', 'Handcrafted level 1008', 5, 5, 1, 'published', '{"id":1008,"name":"Introductory Challenge 8","board":{"width":5,"height":5},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":3,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":3,"y":2},{"x":3,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1008,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 9', 'Handcrafted level 1009', 6, 6, 1, 'published', '{"id":1009,"name":"Introductory Challenge 9","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1009,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Introductory Challenge 10', 'Handcrafted level 1010', 5, 5, 1, 'published', '{"id":1010,"name":"Introductory Challenge 10","board":{"width":5,"height":5},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":3,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":3,"y":3},{"x":1,"y":3}]}],"difficulty":1,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1010,"difficultyScore":1}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 1', 'Handcrafted level 1011', 8, 8, 2, 'published', '{"id":1011,"name":"Zigzag & Spiral 1","board":{"width":8,"height":8},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":1,"y":6}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":5},{"x":1,"y":2}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1011,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 2', 'Handcrafted level 1012', 6, 6, 2, 'published', '{"id":1012,"name":"Zigzag & Spiral 2","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":2,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1012,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 3', 'Handcrafted level 1013', 7, 7, 2, 'published', '{"id":1013,"name":"Zigzag & Spiral 3","board":{"width":7,"height":7},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":5,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":5,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":5,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1013,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 4', 'Handcrafted level 1014', 8, 8, 2, 'published', '{"id":1014,"name":"Zigzag & Spiral 4","board":{"width":8,"height":8},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":6,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":6,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1014,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 5', 'Handcrafted level 1015', 6, 6, 2, 'published', '{"id":1015,"name":"Zigzag & Spiral 5","board":{"width":6,"height":6},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":4,"y":2},{"x":4,"y":4}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":3,"y":4},{"x":1,"y":4}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":3},{"x":1,"y":2}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1015,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 6', 'Handcrafted level 1016', 7, 7, 2, 'published', '{"id":1016,"name":"Zigzag & Spiral 6","board":{"width":7,"height":7},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":5,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":5,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":5,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1016,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 7', 'Handcrafted level 1017', 8, 8, 2, 'published', '{"id":1017,"name":"Zigzag & Spiral 7","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1017,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 8', 'Handcrafted level 1018', 6, 6, 2, 'published', '{"id":1018,"name":"Zigzag & Spiral 8","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":2,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1018,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 9', 'Handcrafted level 1019', 7, 7, 2, 'published', '{"id":1019,"name":"Zigzag & Spiral 9","board":{"width":7,"height":7},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":5,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":5,"y":2},{"x":5,"y":5}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":4,"y":5},{"x":1,"y":5}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":4},{"x":1,"y":2}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1019,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 10', 'Handcrafted level 1020', 8, 8, 2, 'published', '{"id":1020,"name":"Zigzag & Spiral 10","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1020,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 11', 'Handcrafted level 1021', 6, 6, 2, 'published', '{"id":1021,"name":"Zigzag & Spiral 11","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":2,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1021,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 12', 'Handcrafted level 1022', 7, 7, 2, 'published', '{"id":1022,"name":"Zigzag & Spiral 12","board":{"width":7,"height":7},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":5,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":5,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":5,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1022,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 13', 'Handcrafted level 1023', 8, 8, 2, 'published', '{"id":1023,"name":"Zigzag & Spiral 13","board":{"width":8,"height":8},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":1,"y":6}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":5},{"x":1,"y":2}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1023,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 14', 'Handcrafted level 1024', 6, 6, 2, 'published', '{"id":1024,"name":"Zigzag & Spiral 14","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":2,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1024,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 15', 'Handcrafted level 1025', 7, 7, 2, 'published', '{"id":1025,"name":"Zigzag & Spiral 15","board":{"width":7,"height":7},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":5,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":5,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":5,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1025,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 16', 'Handcrafted level 1026', 8, 8, 2, 'published', '{"id":1026,"name":"Zigzag & Spiral 16","board":{"width":8,"height":8},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":6,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":6,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1026,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 17', 'Handcrafted level 1027', 6, 6, 2, 'published', '{"id":1027,"name":"Zigzag & Spiral 17","board":{"width":6,"height":6},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":4,"y":2},{"x":4,"y":4}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":3,"y":4},{"x":1,"y":4}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":3},{"x":1,"y":2}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1027,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 18', 'Handcrafted level 1028', 7, 7, 2, 'published', '{"id":1028,"name":"Zigzag & Spiral 18","board":{"width":7,"height":7},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":5,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":5,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":5,"y":5}]}],"difficulty":2,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1028,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 19', 'Handcrafted level 1029', 8, 8, 2, 'published', '{"id":1029,"name":"Zigzag & Spiral 19","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":2,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1029,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Zigzag & Spiral 20', 'Handcrafted level 1030', 6, 6, 2, 'published', '{"id":1030,"name":"Zigzag & Spiral 20","board":{"width":6,"height":6},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":4,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":4,"y":3},{"x":1,"y":3}]}],"difficulty":2,"parMoves":2,"patternType":"CUSTOM_COLLECTION","seed":1030,"difficultyScore":2}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 1', 'Handcrafted level 1031', 9, 9, 3, 'published', '{"id":1031,"name":"Concentric Loop 1","board":{"width":9,"height":9},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":7,"y":2},{"x":7,"y":7}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":6,"y":7},{"x":1,"y":7}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":6},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":5,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":5,"y":4},{"x":5,"y":5}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":4,"y":5},{"x":3,"y":5}]}],"difficulty":3,"parMoves":7,"patternType":"CUSTOM_COLLECTION","seed":1031,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 2', 'Handcrafted level 1032', 10, 10, 3, 'published', '{"id":1032,"name":"Concentric Loop 2","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1032,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 3', 'Handcrafted level 1033', 8, 8, 3, 'published', '{"id":1033,"name":"Concentric Loop 3","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1033,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 4', 'Handcrafted level 1034', 9, 9, 3, 'published', '{"id":1034,"name":"Concentric Loop 4","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1034,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 5', 'Handcrafted level 1035', 10, 10, 3, 'published', '{"id":1035,"name":"Concentric Loop 5","board":{"width":10,"height":10},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":8,"y":2},{"x":8,"y":8}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":1,"y":8}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":7},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":6,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":6,"y":4},{"x":6,"y":6}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":3,"y":6}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":5},{"x":3,"y":4}]}],"difficulty":3,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1035,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 6', 'Handcrafted level 1036', 8, 8, 3, 'published', '{"id":1036,"name":"Concentric Loop 6","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1036,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 7', 'Handcrafted level 1037', 9, 9, 3, 'published', '{"id":1037,"name":"Concentric Loop 7","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1037,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 8', 'Handcrafted level 1038', 10, 10, 3, 'published', '{"id":1038,"name":"Concentric Loop 8","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1038,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 9', 'Handcrafted level 1039', 8, 8, 3, 'published', '{"id":1039,"name":"Concentric Loop 9","board":{"width":8,"height":8},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":1,"y":6}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":5},{"x":1,"y":2}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1039,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 10', 'Handcrafted level 1040', 9, 9, 3, 'published', '{"id":1040,"name":"Concentric Loop 10","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1040,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 11', 'Handcrafted level 1041', 10, 10, 3, 'published', '{"id":1041,"name":"Concentric Loop 11","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1041,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 12', 'Handcrafted level 1042', 8, 8, 3, 'published', '{"id":1042,"name":"Concentric Loop 12","board":{"width":8,"height":8},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":6,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":6,"y":5}]}],"difficulty":3,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1042,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 13', 'Handcrafted level 1043', 9, 9, 3, 'published', '{"id":1043,"name":"Concentric Loop 13","board":{"width":9,"height":9},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":7,"y":2},{"x":7,"y":7}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":6,"y":7},{"x":1,"y":7}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":6},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":5,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":5,"y":4},{"x":5,"y":5}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":4,"y":5},{"x":3,"y":5}]}],"difficulty":3,"parMoves":7,"patternType":"CUSTOM_COLLECTION","seed":1043,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 14', 'Handcrafted level 1044', 10, 10, 3, 'published', '{"id":1044,"name":"Concentric Loop 14","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1044,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 15', 'Handcrafted level 1045', 8, 8, 3, 'published', '{"id":1045,"name":"Concentric Loop 15","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1045,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 16', 'Handcrafted level 1046', 9, 9, 3, 'published', '{"id":1046,"name":"Concentric Loop 16","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1046,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 17', 'Handcrafted level 1047', 10, 10, 3, 'published', '{"id":1047,"name":"Concentric Loop 17","board":{"width":10,"height":10},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":8,"y":2},{"x":8,"y":8}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":1,"y":8}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":7},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":6,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":6,"y":4},{"x":6,"y":6}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":3,"y":6}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":5},{"x":3,"y":4}]}],"difficulty":3,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1047,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 18', 'Handcrafted level 1048', 8, 8, 3, 'published', '{"id":1048,"name":"Concentric Loop 18","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1048,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 19', 'Handcrafted level 1049', 9, 9, 3, 'published', '{"id":1049,"name":"Concentric Loop 19","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1049,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 20', 'Handcrafted level 1050', 10, 10, 3, 'published', '{"id":1050,"name":"Concentric Loop 20","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1050,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 21', 'Handcrafted level 1051', 8, 8, 3, 'published', '{"id":1051,"name":"Concentric Loop 21","board":{"width":8,"height":8},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":1,"y":6}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":5},{"x":1,"y":2}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1051,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 22', 'Handcrafted level 1052', 9, 9, 3, 'published', '{"id":1052,"name":"Concentric Loop 22","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1052,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 23', 'Handcrafted level 1053', 10, 10, 3, 'published', '{"id":1053,"name":"Concentric Loop 23","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1053,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 24', 'Handcrafted level 1054', 8, 8, 3, 'published', '{"id":1054,"name":"Concentric Loop 24","board":{"width":8,"height":8},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":6,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":6,"y":5}]}],"difficulty":3,"parMoves":3,"patternType":"CUSTOM_COLLECTION","seed":1054,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 25', 'Handcrafted level 1055', 9, 9, 3, 'published', '{"id":1055,"name":"Concentric Loop 25","board":{"width":9,"height":9},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":7,"y":2},{"x":7,"y":7}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":6,"y":7},{"x":1,"y":7}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":6},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":5,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":5,"y":4},{"x":5,"y":5}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":4,"y":5},{"x":3,"y":5}]}],"difficulty":3,"parMoves":7,"patternType":"CUSTOM_COLLECTION","seed":1055,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 26', 'Handcrafted level 1056', 10, 10, 3, 'published', '{"id":1056,"name":"Concentric Loop 26","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1056,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 27', 'Handcrafted level 1057', 8, 8, 3, 'published', '{"id":1057,"name":"Concentric Loop 27","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1057,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 28', 'Handcrafted level 1058', 9, 9, 3, 'published', '{"id":1058,"name":"Concentric Loop 28","board":{"width":9,"height":9},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":7,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":7,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":7,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":7,"y":7},{"x":1,"y":7}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1058,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 29', 'Handcrafted level 1059', 10, 10, 3, 'published', '{"id":1059,"name":"Concentric Loop 29","board":{"width":10,"height":10},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":8,"y":2},{"x":8,"y":8}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":1,"y":8}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":7},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":6,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":6,"y":4},{"x":6,"y":6}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":3,"y":6}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":5},{"x":3,"y":4}]}],"difficulty":3,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1059,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Concentric Loop 30', 'Handcrafted level 1060', 8, 8, 3, 'published', '{"id":1060,"name":"Concentric Loop 30","board":{"width":8,"height":8},"arrows":[{"id":"c_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":6,"y":1}]},{"id":"c_0_2","direction":"DOWN","points":[{"x":6,"y":2},{"x":6,"y":6}]},{"id":"c_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":4,"y":3}]},{"id":"c_1_2","direction":"DOWN","points":[{"x":4,"y":4},{"x":4,"y":4}]}],"difficulty":3,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1060,"difficultyScore":3}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 1', 'Handcrafted level 1061', 11, 11, 4, 'published', '{"id":1061,"name":"Interlocking Maze 1","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1061,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 2', 'Handcrafted level 1062', 12, 12, 4, 'published', '{"id":1062,"name":"Interlocking Maze 2","board":{"width":12,"height":12},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":10,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":10,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":10,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":10,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1062,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 3', 'Handcrafted level 1063', 10, 10, 4, 'published', '{"id":1063,"name":"Interlocking Maze 3","board":{"width":10,"height":10},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":8,"y":2},{"x":8,"y":8}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":1,"y":8}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":7},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":6,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":6,"y":4},{"x":6,"y":6}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":3,"y":6}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":5},{"x":3,"y":4}]}],"difficulty":4,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1063,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 4', 'Handcrafted level 1064', 11, 11, 4, 'published', '{"id":1064,"name":"Interlocking Maze 4","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1064,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 5', 'Handcrafted level 1065', 12, 12, 4, 'published', '{"id":1065,"name":"Interlocking Maze 5","board":{"width":12,"height":12},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":10,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":10,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":10,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":10,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1065,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 6', 'Handcrafted level 1066', 10, 10, 4, 'published', '{"id":1066,"name":"Interlocking Maze 6","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":4,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1066,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 7', 'Handcrafted level 1067', 11, 11, 4, 'published', '{"id":1067,"name":"Interlocking Maze 7","board":{"width":11,"height":11},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":9,"y":2},{"x":9,"y":9}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":8,"y":9},{"x":1,"y":9}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":8},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":7,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":7,"y":4},{"x":7,"y":7}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":6,"y":7},{"x":3,"y":7}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":6},{"x":3,"y":4}]}],"difficulty":4,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1067,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 8', 'Handcrafted level 1068', 12, 12, 4, 'published', '{"id":1068,"name":"Interlocking Maze 8","board":{"width":12,"height":12},"arrows":[{"id":"l_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":1,"y":3},{"x":3,"y":3}]},{"id":"h_2","direction":"RIGHT","points":[{"x":1,"y":4},{"x":3,"y":4}]},{"id":"l_3","direction":"RIGHT","points":[{"x":1,"y":7},{"x":1,"y":9},{"x":3,"y":9}]},{"id":"h_4","direction":"RIGHT","points":[{"x":1,"y":10},{"x":3,"y":10}]},{"id":"l_5","direction":"RIGHT","points":[{"x":4,"y":1},{"x":4,"y":3},{"x":6,"y":3}]},{"id":"h_6","direction":"RIGHT","points":[{"x":4,"y":4},{"x":6,"y":4}]},{"id":"l_7","direction":"RIGHT","points":[{"x":4,"y":7},{"x":4,"y":9},{"x":6,"y":9}]},{"id":"h_8","direction":"RIGHT","points":[{"x":4,"y":10},{"x":6,"y":10}]},{"id":"l_9","direction":"RIGHT","points":[{"x":7,"y":1},{"x":7,"y":3},{"x":9,"y":3}]}],"difficulty":4,"parMoves":9,"patternType":"CUSTOM_COLLECTION","seed":1068,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 9', 'Handcrafted level 1069', 10, 10, 4, 'published', '{"id":1069,"name":"Interlocking Maze 9","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":4,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1069,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 10', 'Handcrafted level 1070', 11, 11, 4, 'published', '{"id":1070,"name":"Interlocking Maze 10","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1070,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 11', 'Handcrafted level 1071', 12, 12, 4, 'published', '{"id":1071,"name":"Interlocking Maze 11","board":{"width":12,"height":12},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":10,"y":2},{"x":10,"y":10}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":9,"y":10},{"x":1,"y":10}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":9},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":8,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":8,"y":4},{"x":8,"y":8}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":3,"y":8}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":7},{"x":3,"y":4}]}],"difficulty":4,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1071,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 12', 'Handcrafted level 1072', 10, 10, 4, 'published', '{"id":1072,"name":"Interlocking Maze 12","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":4,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1072,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 13', 'Handcrafted level 1073', 11, 11, 4, 'published', '{"id":1073,"name":"Interlocking Maze 13","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1073,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 14', 'Handcrafted level 1074', 12, 12, 4, 'published', '{"id":1074,"name":"Interlocking Maze 14","board":{"width":12,"height":12},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":10,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":10,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":10,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":10,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1074,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 15', 'Handcrafted level 1075', 10, 10, 4, 'published', '{"id":1075,"name":"Interlocking Maze 15","board":{"width":10,"height":10},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":8,"y":2},{"x":8,"y":8}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":1,"y":8}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":7},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":6,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":6,"y":4},{"x":6,"y":6}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":5,"y":6},{"x":3,"y":6}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":5},{"x":3,"y":4}]}],"difficulty":4,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1075,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 16', 'Handcrafted level 1076', 11, 11, 4, 'published', '{"id":1076,"name":"Interlocking Maze 16","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1076,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 17', 'Handcrafted level 1077', 12, 12, 4, 'published', '{"id":1077,"name":"Interlocking Maze 17","board":{"width":12,"height":12},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":10,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":10,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":10,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":10,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1077,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 18', 'Handcrafted level 1078', 10, 10, 4, 'published', '{"id":1078,"name":"Interlocking Maze 18","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":4,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1078,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 19', 'Handcrafted level 1079', 11, 11, 4, 'published', '{"id":1079,"name":"Interlocking Maze 19","board":{"width":11,"height":11},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":9,"y":2},{"x":9,"y":9}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":8,"y":9},{"x":1,"y":9}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":8},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":7,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":7,"y":4},{"x":7,"y":7}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":6,"y":7},{"x":3,"y":7}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":6},{"x":3,"y":4}]}],"difficulty":4,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1079,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 20', 'Handcrafted level 1080', 12, 12, 4, 'published', '{"id":1080,"name":"Interlocking Maze 20","board":{"width":12,"height":12},"arrows":[{"id":"l_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":1,"y":3},{"x":3,"y":3}]},{"id":"h_2","direction":"RIGHT","points":[{"x":1,"y":4},{"x":3,"y":4}]},{"id":"l_3","direction":"RIGHT","points":[{"x":1,"y":7},{"x":1,"y":9},{"x":3,"y":9}]},{"id":"h_4","direction":"RIGHT","points":[{"x":1,"y":10},{"x":3,"y":10}]},{"id":"l_5","direction":"RIGHT","points":[{"x":4,"y":1},{"x":4,"y":3},{"x":6,"y":3}]},{"id":"h_6","direction":"RIGHT","points":[{"x":4,"y":4},{"x":6,"y":4}]},{"id":"l_7","direction":"RIGHT","points":[{"x":4,"y":7},{"x":4,"y":9},{"x":6,"y":9}]},{"id":"h_8","direction":"RIGHT","points":[{"x":4,"y":10},{"x":6,"y":10}]},{"id":"l_9","direction":"RIGHT","points":[{"x":7,"y":1},{"x":7,"y":3},{"x":9,"y":3}]}],"difficulty":4,"parMoves":9,"patternType":"CUSTOM_COLLECTION","seed":1080,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 21', 'Handcrafted level 1081', 10, 10, 4, 'published', '{"id":1081,"name":"Interlocking Maze 21","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":4,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1081,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 22', 'Handcrafted level 1082', 11, 11, 4, 'published', '{"id":1082,"name":"Interlocking Maze 22","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1082,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 23', 'Handcrafted level 1083', 12, 12, 4, 'published', '{"id":1083,"name":"Interlocking Maze 23","board":{"width":12,"height":12},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":10,"y":2},{"x":10,"y":10}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":9,"y":10},{"x":1,"y":10}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":9},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":8,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":8,"y":4},{"x":8,"y":8}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":3,"y":8}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":7},{"x":3,"y":4}]}],"difficulty":4,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1083,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 24', 'Handcrafted level 1084', 10, 10, 4, 'published', '{"id":1084,"name":"Interlocking Maze 24","board":{"width":10,"height":10},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":8,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":8,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":8,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":8,"y":7},{"x":1,"y":7}]}],"difficulty":4,"parMoves":4,"patternType":"CUSTOM_COLLECTION","seed":1084,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Interlocking Maze 25', 'Handcrafted level 1085', 11, 11, 4, 'published', '{"id":1085,"name":"Interlocking Maze 25","board":{"width":11,"height":11},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":9,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":9,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":9,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":9,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":9,"y":9}]}],"difficulty":4,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1085,"difficultyScore":4}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 1', 'Handcrafted level 1086', 14, 14, 5, 'published', '{"id":1086,"name":"Master Escape 1","board":{"width":14,"height":14},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":12,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":12,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":12,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":12,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":12,"y":9}]},{"id":"z_11","direction":"LEFT","points":[{"x":12,"y":11},{"x":1,"y":11}]}],"difficulty":5,"parMoves":6,"patternType":"CUSTOM_COLLECTION","seed":1086,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 2', 'Handcrafted level 1087', 12, 12, 5, 'published', '{"id":1087,"name":"Master Escape 2","board":{"width":12,"height":12},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":10,"y":2},{"x":10,"y":10}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":9,"y":10},{"x":1,"y":10}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":9},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":8,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":8,"y":4},{"x":8,"y":8}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":3,"y":8}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":7},{"x":3,"y":4}]}],"difficulty":5,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1087,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 3', 'Handcrafted level 1088', 13, 13, 5, 'published', '{"id":1088,"name":"Master Escape 3","board":{"width":13,"height":13},"arrows":[{"id":"l_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":1,"y":3},{"x":3,"y":3}]},{"id":"h_2","direction":"RIGHT","points":[{"x":1,"y":4},{"x":3,"y":4}]},{"id":"l_3","direction":"RIGHT","points":[{"x":1,"y":7},{"x":1,"y":9},{"x":3,"y":9}]},{"id":"h_4","direction":"RIGHT","points":[{"x":1,"y":10},{"x":3,"y":10}]},{"id":"l_5","direction":"RIGHT","points":[{"x":4,"y":1},{"x":4,"y":3},{"x":6,"y":3}]},{"id":"h_6","direction":"RIGHT","points":[{"x":4,"y":4},{"x":6,"y":4}]},{"id":"l_7","direction":"RIGHT","points":[{"x":4,"y":7},{"x":4,"y":9},{"x":6,"y":9}]},{"id":"h_8","direction":"RIGHT","points":[{"x":4,"y":10},{"x":6,"y":10}]},{"id":"l_9","direction":"RIGHT","points":[{"x":7,"y":1},{"x":7,"y":3},{"x":9,"y":3}]},{"id":"h_10","direction":"RIGHT","points":[{"x":7,"y":4},{"x":9,"y":4}]}],"difficulty":5,"parMoves":10,"patternType":"CUSTOM_COLLECTION","seed":1088,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 4', 'Handcrafted level 1089', 14, 14, 5, 'published', '{"id":1089,"name":"Master Escape 4","board":{"width":14,"height":14},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":12,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":12,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":12,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":12,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":12,"y":9}]},{"id":"z_11","direction":"LEFT","points":[{"x":12,"y":11},{"x":1,"y":11}]}],"difficulty":5,"parMoves":6,"patternType":"CUSTOM_COLLECTION","seed":1089,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 5', 'Handcrafted level 1090', 12, 12, 5, 'published', '{"id":1090,"name":"Master Escape 5","board":{"width":12,"height":12},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":10,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":10,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":10,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":10,"y":9}]}],"difficulty":5,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1090,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 6', 'Handcrafted level 1091', 13, 13, 5, 'published', '{"id":1091,"name":"Master Escape 6","board":{"width":13,"height":13},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":11,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":11,"y":2},{"x":11,"y":11}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":10,"y":11},{"x":1,"y":11}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":10},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":9,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":9,"y":4},{"x":9,"y":9}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":8,"y":9},{"x":3,"y":9}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":8},{"x":3,"y":4}]},{"id":"a_2_1","direction":"RIGHT","points":[{"x":5,"y":5},{"x":7,"y":5}]},{"id":"a_2_2","direction":"DOWN","points":[{"x":7,"y":6},{"x":7,"y":7}]}],"difficulty":5,"parMoves":10,"patternType":"CUSTOM_COLLECTION","seed":1091,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 7', 'Handcrafted level 1092', 14, 14, 5, 'published', '{"id":1092,"name":"Master Escape 7","board":{"width":14,"height":14},"arrows":[{"id":"l_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":1,"y":3},{"x":3,"y":3}]},{"id":"h_2","direction":"RIGHT","points":[{"x":1,"y":4},{"x":3,"y":4}]},{"id":"l_3","direction":"RIGHT","points":[{"x":1,"y":7},{"x":1,"y":9},{"x":3,"y":9}]},{"id":"h_4","direction":"RIGHT","points":[{"x":1,"y":10},{"x":3,"y":10}]},{"id":"l_5","direction":"RIGHT","points":[{"x":4,"y":1},{"x":4,"y":3},{"x":6,"y":3}]},{"id":"h_6","direction":"RIGHT","points":[{"x":4,"y":4},{"x":6,"y":4}]},{"id":"l_7","direction":"RIGHT","points":[{"x":4,"y":7},{"x":4,"y":9},{"x":6,"y":9}]},{"id":"h_8","direction":"RIGHT","points":[{"x":4,"y":10},{"x":6,"y":10}]},{"id":"l_9","direction":"RIGHT","points":[{"x":7,"y":1},{"x":7,"y":3},{"x":9,"y":3}]},{"id":"h_10","direction":"RIGHT","points":[{"x":7,"y":4},{"x":9,"y":4}]},{"id":"l_11","direction":"RIGHT","points":[{"x":7,"y":7},{"x":7,"y":9},{"x":9,"y":9}]}],"difficulty":5,"parMoves":11,"patternType":"CUSTOM_COLLECTION","seed":1092,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 8', 'Handcrafted level 1093', 12, 12, 5, 'published', '{"id":1093,"name":"Master Escape 8","board":{"width":12,"height":12},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":10,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":10,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":10,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":10,"y":9}]}],"difficulty":5,"parMoves":5,"patternType":"CUSTOM_COLLECTION","seed":1093,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 9', 'Handcrafted level 1094', 13, 13, 5, 'published', '{"id":1094,"name":"Master Escape 9","board":{"width":13,"height":13},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":11,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":11,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":11,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":11,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":11,"y":9}]},{"id":"z_11","direction":"LEFT","points":[{"x":11,"y":11},{"x":1,"y":11}]}],"difficulty":5,"parMoves":6,"patternType":"CUSTOM_COLLECTION","seed":1094,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 10', 'Handcrafted level 1095', 14, 14, 5, 'published', '{"id":1095,"name":"Master Escape 10","board":{"width":14,"height":14},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":12,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":12,"y":2},{"x":12,"y":12}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":11,"y":12},{"x":1,"y":12}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":11},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":10,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":10,"y":4},{"x":10,"y":10}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":9,"y":10},{"x":3,"y":10}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":9},{"x":3,"y":4}]},{"id":"a_2_1","direction":"RIGHT","points":[{"x":5,"y":5},{"x":8,"y":5}]},{"id":"a_2_2","direction":"DOWN","points":[{"x":8,"y":6},{"x":8,"y":8}]},{"id":"a_2_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":5,"y":8}]}],"difficulty":5,"parMoves":11,"patternType":"CUSTOM_COLLECTION","seed":1095,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 11', 'Handcrafted level 1096', 12, 12, 5, 'published', '{"id":1096,"name":"Master Escape 11","board":{"width":12,"height":12},"arrows":[{"id":"l_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":1,"y":3},{"x":3,"y":3}]},{"id":"h_2","direction":"RIGHT","points":[{"x":1,"y":4},{"x":3,"y":4}]},{"id":"l_3","direction":"RIGHT","points":[{"x":1,"y":7},{"x":1,"y":9},{"x":3,"y":9}]},{"id":"h_4","direction":"RIGHT","points":[{"x":1,"y":10},{"x":3,"y":10}]},{"id":"l_5","direction":"RIGHT","points":[{"x":4,"y":1},{"x":4,"y":3},{"x":6,"y":3}]},{"id":"h_6","direction":"RIGHT","points":[{"x":4,"y":4},{"x":6,"y":4}]},{"id":"l_7","direction":"RIGHT","points":[{"x":4,"y":7},{"x":4,"y":9},{"x":6,"y":9}]},{"id":"h_8","direction":"RIGHT","points":[{"x":4,"y":10},{"x":6,"y":10}]},{"id":"l_9","direction":"RIGHT","points":[{"x":7,"y":1},{"x":7,"y":3},{"x":9,"y":3}]}],"difficulty":5,"parMoves":9,"patternType":"CUSTOM_COLLECTION","seed":1096,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 12', 'Handcrafted level 1097', 13, 13, 5, 'published', '{"id":1097,"name":"Master Escape 12","board":{"width":13,"height":13},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":11,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":11,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":11,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":11,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":11,"y":9}]},{"id":"z_11","direction":"LEFT","points":[{"x":11,"y":11},{"x":1,"y":11}]}],"difficulty":5,"parMoves":6,"patternType":"CUSTOM_COLLECTION","seed":1097,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 13', 'Handcrafted level 1098', 14, 14, 5, 'published', '{"id":1098,"name":"Master Escape 13","board":{"width":14,"height":14},"arrows":[{"id":"z_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":12,"y":1}]},{"id":"z_3","direction":"LEFT","points":[{"x":12,"y":3},{"x":1,"y":3}]},{"id":"z_5","direction":"RIGHT","points":[{"x":1,"y":5},{"x":12,"y":5}]},{"id":"z_7","direction":"LEFT","points":[{"x":12,"y":7},{"x":1,"y":7}]},{"id":"z_9","direction":"RIGHT","points":[{"x":1,"y":9},{"x":12,"y":9}]},{"id":"z_11","direction":"LEFT","points":[{"x":12,"y":11},{"x":1,"y":11}]}],"difficulty":5,"parMoves":6,"patternType":"CUSTOM_COLLECTION","seed":1098,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 14', 'Handcrafted level 1099', 12, 12, 5, 'published', '{"id":1099,"name":"Master Escape 14","board":{"width":12,"height":12},"arrows":[{"id":"a_0_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":10,"y":1}]},{"id":"a_0_2","direction":"DOWN","points":[{"x":10,"y":2},{"x":10,"y":10}]},{"id":"a_0_3","direction":"LEFT","points":[{"x":9,"y":10},{"x":1,"y":10}]},{"id":"a_0_4","direction":"UP","points":[{"x":1,"y":9},{"x":1,"y":2}]},{"id":"a_1_1","direction":"RIGHT","points":[{"x":3,"y":3},{"x":8,"y":3}]},{"id":"a_1_2","direction":"DOWN","points":[{"x":8,"y":4},{"x":8,"y":8}]},{"id":"a_1_3","direction":"LEFT","points":[{"x":7,"y":8},{"x":3,"y":8}]},{"id":"a_1_4","direction":"UP","points":[{"x":3,"y":7},{"x":3,"y":4}]}],"difficulty":5,"parMoves":8,"patternType":"CUSTOM_COLLECTION","seed":1099,"difficultyScore":5}'::jsonb, now());

INSERT INTO public.custom_patterns (name, description, width, height, difficulty, status, level_data, published_at)
VALUES ('Master Escape 15', 'Handcrafted level 1100', 13, 13, 5, 'published', '{"id":1100,"name":"Master Escape 15","board":{"width":13,"height":13},"arrows":[{"id":"l_1","direction":"RIGHT","points":[{"x":1,"y":1},{"x":1,"y":3},{"x":3,"y":3}]},{"id":"h_2","direction":"RIGHT","points":[{"x":1,"y":4},{"x":3,"y":4}]},{"id":"l_3","direction":"RIGHT","points":[{"x":1,"y":7},{"x":1,"y":9},{"x":3,"y":9}]},{"id":"h_4","direction":"RIGHT","points":[{"x":1,"y":10},{"x":3,"y":10}]},{"id":"l_5","direction":"RIGHT","points":[{"x":4,"y":1},{"x":4,"y":3},{"x":6,"y":3}]},{"id":"h_6","direction":"RIGHT","points":[{"x":4,"y":4},{"x":6,"y":4}]},{"id":"l_7","direction":"RIGHT","points":[{"x":4,"y":7},{"x":4,"y":9},{"x":6,"y":9}]},{"id":"h_8","direction":"RIGHT","points":[{"x":4,"y":10},{"x":6,"y":10}]},{"id":"l_9","direction":"RIGHT","points":[{"x":7,"y":1},{"x":7,"y":3},{"x":9,"y":3}]},{"id":"h_10","direction":"RIGHT","points":[{"x":7,"y":4},{"x":9,"y":4}]}],"difficulty":5,"parMoves":10,"patternType":"CUSTOM_COLLECTION","seed":1100,"difficultyScore":5}'::jsonb, now());

